### ISSUE TITLE
damageFactor returns 1 instead of 2 for zealot attack

### ISSUE THREAD

**Issue by ufsqufbqifbqibfuiq** [bwapi/bwapi#694] opened 2016-11-30 23:08 UTC
The damage delivered by a zealot attack (Pis blades) is 2 * 8 = 16

`damageAmount()` is ok (returns 8) but `damageFactor()` should return 2 (currently returns 1)

it's because `wpnDamageFactor[64]` is 1 (`WeaponTypes::Enum::Psi_Blades` = 64)
https://github.com/bwapi/bwapi/blob/38343b0263e7de72f4a7ab66d897a879b4a97802/bwapi/BWAPILIB/Source/WeaponType.cpp#L179

or maybe I am missing something ?

**Comment by albertouri** [comment] 2016-11-30 23:14
You also have to use maxGroundHits(), which it's two for Zealots ;)

**Comment by ufsqufbqifbqibfuiq** [comment] 2016-11-30 23:24
Oh! I didn't know this function exited! Thank you!

but then PlayerInterface::damage implementation is wrong ?
https://github.com/bwapi/bwapi/blob/38343b0263e7de72f4a7ab66d897a879b4a97802/bwapi/BWAPILIB/Source/Player.cpp#L106

and also getDamageFromImpl ? 
https://github.com/bwapi/bwapi/blob/38343b0263e7de72f4a7ab66d897a879b4a97802/bwapi/BWAPILIB/Source/Game.cpp#L69

**Comment by albertouri** [comment] 2016-11-30 23:55
Good points.

PlayerInterface::damage is correct, since it's only relative to the weapon.

But getDamageFromImpl is missing the maxGroundHits() since it knows the unit type. Therefore this should be fixed.

There is also an error on line 77 https://github.com/bwapi/bwapi/blob/38343b0263e7de72f4a7ab66d897a879b4a97802/bwapi/BWAPILIB/Source/Game.cpp#L77
The else case doesn't take into acount the weapon's upgrades.

If you are wondering why we have damageFactor and maxGroundHits/maxAirHits, it's because a hit has a small chance to fail, ie. a Zealot attack can miss one or two of the psi_blades attacks

**Comment by ufsqufbqifbqibfuiq** [comment] 2016-12-01 00:39
Ok, now I understand, `Psi_Blades` is in fact only **one** "blade", but a zealot has **two** `Psi_Blades`.
So `Psi_Blades` damage doesn't have a factor 2, the zealot has.

However, a goliath has **one** `Hellfire_Missile_Pack` (`maxAirHits` = 1), but the  `Hellfire_Missile_Pack` launches **two** rockets (`damageFactor` = 2).

Am I right ?

**Comment by albertouri** [comment] 2016-12-01 00:43
Yes. If the rocket impacts the target, both of them impact; while the zealot can miss none, one or two of the blades attack.

**Comment by ufsqufbqifbqibfuiq** [comment] 2016-12-01 00:56
I see. Thank you!

Also, is this correct ? `dmg -= std::min(dmg, toPlayer->armor(toType));`
https://github.com/bwapi/bwapi/blob/38343b0263e7de72f4a7ab66d897a879b4a97802/bwapi/BWAPILIB/Source/Game.cpp#L81

It seems that dmg can be 0. I thought the minimum damage was 1.

**Comment by albertouri** [comment] 2016-12-01 01:04
Probably is to avoid unexpected behavior (dmg going negative) but I don't
think there is a unit with a lower damage than the maximum armor of another
unit.

**Comment by ufsqufbqifbqibfuiq** [comment] 2016-12-01 01:22
The Ultralisk can have 6 armor (1 base + 3 from upgrade + 2 from Chitinous Plating). The marine has a 6 base attack, so getDamageFromImpl would return a damage of 0.

I think in this case the marines still make 1 damage.

**Comment by albertouri** [comment] 2016-12-01 01:40
Oh true! 
In fact the minimum damage is 0.5, that means we need to change the dmg variable to a float...

Arg, damn edge cases... :P

[Off topic] What are you trying to do? Your are going into too low level detail. These functions are designed to have an approximation since the damage inflicted depends also on the shield [\Off topic]

**Comment by ufsqufbqifbqibfuiq** [comment] 2016-12-01 01:50
I am trying to compute an approximate survival time of a group of unit vs another group of unit. I was getting strange results when fighting zealots, because of my ignorance of `maxGroundHits` function... Then I began to dig in BWAPI source code, and couldn't help nitpickning...

However, about the 0.5 damage, if my 50 non-upgraded marines are fighting 1 fully upagraded ultralisk, I would get infinite survival time for the ultralisk, and my marines would retreat instead of attacking... So this low level stuff may be important in some cases.

Anyway, my bot probably have other greater problems than this ;)

**Closed** 2019-03-07 13:54 UTC
