### ISSUE TITLE
Possible desired behavior inconsistency in BWAPI::Player::allUnitCount

### ISSUE THREAD

**Issue by davechurchill** [bwapi/bwapi#622] opened 2015-09-28 05:27 UTC
For terran and protoss, this count will factor in units current under construction (because the unit exists on the map while being produced)

For zerg, it will not factor in units which are currently inside eggs. Is this intentional?

**Comment by heinermann** [comment] 2016-08-08 03:48
This is intentional, given that: When units are training, they physically exist within the game as new entities. When units are morphing, they are just larvae becoming eggs (so they count as eggs).

I'm not sure what kind of strategy I would use to deal with it.

**Comment by heinermann** [comment] 2016-08-08 03:50
Actually I will investigate if there is a difference in behaviour with StarEdit Triggers and BWAPI, and get back to the issue with the "official" behaviour.

**Comment by heinermann** [comment] 2016-08-08 06:33
OK I've just confirmed that this is the same way it works in the Broodwar engine.

Sample code:
~~~cpp
  drawTextScreen(100, 100, "SCVs: (%d / %d)\nDrones: (%d / %d)",
    BW::BWDATA::Game.unitCounts.all[UnitTypes::Terran_SCV][0],
    BW::BWDATA::Game.unitCounts.completed[UnitTypes::Terran_SCV][0],
    BW::BWDATA::Game.unitCounts.all[UnitTypes::Zerg_Drone][0],
    BW::BWDATA::Game.unitCounts.completed[UnitTypes::Zerg_Drone][0]);
~~~

1 when an SCV is training and 0 when a Drone is being morphed.

**Comment by heinermann** [comment] 2016-09-28 05:56
Added a note. Closing since it is expected behaviour.

**Closed by heinermann** 2016-09-28 05:56 UTC
Labels: Priority-High
