### ISSUE TITLE
Unable to open communications pipe: \\.\pipe\bwapi_pipe_5780

### ISSUE THREAD

**Issue by lavinoys** [bwapi/bwapi#698] opened 2017-01-15 07:59 UTC
I got this error while running examplebot.

How can solve it?

Connecting to Broodwar...
0 | 5780 | 0 | 1961234
1 | 0 | 0 | 0
2 | 0 | 0 | 0
3 | 0 | 0 | 0
4 | 0 | 0 | 0
5 | 0 | 0 | 0
6 | 0 | 0 | 0
7 | 0 | 0 | 0
Connected
Error: Client and Server are not compatible!
Client Revision: 4615
Server Revision: 4708
0 | 5780 | 0 | 1964250
1 | 0 | 0 | 0
2 | 0 | 0 | 0
3 | 0 | 0 | 0
4 | 0 | 0 | 0
5 | 0 | 0 | 0
6 | 0 | 0 | 0
7 | 0 | 0 | 0
Unable to open communications pipe: \\.\pipe\bwapi_pipe_5780
0 | 5780 | 0 | 1965265
1 | 0 | 0 | 0
2 | 0 | 0 | 0
3 | 0 | 0 | 0
4 | 0 | 0 | 0
5 | 0 | 0 | 0
6 | 0 | 0 | 0
7 | 0 | 0 | 0
Unable to open communications pipe: \\.\pipe\bwapi_pipe_5780
0 | 5780 | 0 | 1966265
1 | 0 | 0 | 0
2 | 0 | 0 | 0
3 | 0 | 0 | 0
4 | 0 | 0 | 0
5 | 0 | 0 | 0
6 | 0 | 0 | 0
7 | 0 | 0 | 0
Unable to open communications pipe: \\.\pipe\bwapi_pipe_5780
0 | 5780 | 0 | 1967281
1 | 0 | 0 | 0
2 | 0 | 0 | 0
3 | 0 | 0 | 0
4 | 0 | 0 | 0
5 | 0 | 0 | 0
6 | 0 | 0 | 0
7 | 0 | 0 | 0
Unable to open communications pipe: \\.\pipe\bwapi_pipe_5780
0 | 5780 | 0 | 1968281
1 | 0 | 0 | 0
2 | 0 | 0 | 0
3 | 0 | 0 | 0
4 | 0 | 0 | 0
5 | 0 | 0 | 0
6 | 0 | 0 | 0
7 | 0 | 0 | 0
Unable to open communications pipe: \\.\pipe\bwapi_pipe_5780
0 | 5780 | 0 | 1969234
1 | 0 | 0 | 0
2 | 0 | 0 | 0
3 | 0 | 0 | 0
4 | 0 | 0 | 0
5 | 0 | 0 | 0
6 | 0 | 0 | 0
7 | 0 | 0 | 0
Unable to open communications pipe: \\.\pipe\bwapi_pipe_5780
0 | 5780 | 0 | 1970250
1 | 0 | 0 | 0
2 | 0 | 0 | 0
3 | 0 | 0 | 0
4 | 0 | 0 | 0
5 | 0 | 0 | 0
6 | 0 | 0 | 0
7 | 0 | 0 | 0
Unable to open communications pipe: \\.\pipe\bwapi_pipe_5780
0 | 5780 | 0 | 1971250
1 | 0 | 0 | 0
2 | 0 | 0 | 0
3 | 0 | 0 | 0
4 | 0 | 0 | 0
5 | 0 | 0 | 0
6 | 0 | 0 | 0
7 | 0 | 0 | 0
Unable to open communications pipe: \\.\pipe\bwapi_pipe_5780
0 | 5780 | 0 | 1972265
1 | 0 | 0 | 0
2 | 0 | 0 | 0
3 | 0 | 0 | 0
4 | 0 | 0 | 0
5 | 0 | 0 | 0
6 | 0 | 0 | 0
7 | 0 | 0 | 0
Unable to open communications pipe: \\.\pipe\bwapi_pipe_5780
0 | 5780 | 0 | 1973265
1 | 0 | 0 | 0
2 | 0 | 0 | 0
3 | 0 | 0 | 0
4 | 0 | 0 | 0
5 | 0 | 0 | 0
6 | 0 | 0 | 0
7 | 0 | 0 | 0
Unable to open communications pipe: \\.\pipe\bwapi_pipe_5780

**Comment by dgant** [comment] 2017-01-21 14:26
I'm getting a similar error when running the BWMirror test bot, and had a similar error running the BWAPI-CLI example bot:

0 | 18120 | 0 | 1491641327
1 | 13584 | 0 | 1484668067
2 | 18844 | 0 | 1485152809
3 | 3504 | 0 | 1485262181
4 | 14904 | 0 | 1485689187
5 | 8360 | 0 | 1486594492
6 | 11760 | 0 | 1486799274
7 | 9980 | 0 | 1488063928
Unable to open communications pipe: \\.\pipe\bwapi_pipe_13584

**Comment by heinermann** [comment] 2017-01-22 02:45
~~~
Error: Client and Server are not compatible!
Client Revision: 4615
Server Revision: 4708
~~~

This was by design. It will be fixed in the next release.

**Comment by dgant** [comment] 2017-01-22 04:28
Turns out my case was just due to phantom copies of Starcraft still running.

**Closed** 2019-03-07 11:05 UTC
