### ISSUE TITLE
Game.getRegionAt() returns Region for invalid positions causing crash

### ISSUE THREAD

**Issue by ratiotile** [bwapi/bwapi#575] opened 2015-04-20 18:12 UTC
If you aren't careful and accidentally get a region from an invalid off-the-map Position, Broodwar will go ahead and return a Region, but it will crash the bot if you access any method on the Region.

The following code crashes the bot.

	  Position pos(-1, -1);
	  BWAPI::Region test_region(Broodwar->getRegionAt(pos));  // everything still OK
	  Broodwar << "Region ID is " << test_region->getID() << " accessible? " << test_region->isAccessible() << std::endl;

Windows 7x64, BWAPI v4.1.0 via ExampleClient, release mode
![image](https://cloud.githubusercontent.com/assets/7064626/7237230/28142b6c-e768-11e4-8fa9-b39afeedf84d.png)

**Comment by ratiotile** [comment] 2015-04-20 18:17
When I run BWAPI and the client in debug mode I get the following error:

![image](https://cloud.githubusercontent.com/assets/7064626/7237183/e3bd7e32-e767-11e4-853a-e72f1d1dae48.png)

**Comment by heinermann** [comment] 2015-04-21 21:44
Can you post the error log for the array subscript out of range? (Found in Broodwar/errors)

**Comment by ratiotile** [comment] 2015-04-21 21:47
The only one I see under Starcraft/Errors is bwapi-error.txt, and it only contains a bunch of:
[2015/04/21 - 21:07:06] Could not find ai under ai in "H:\Games\Starcraft\bwapi-data\bwapi.ini".
[2015/04/21 - 21:30:36] Could not find ai under ai in "H:\Games\Starcraft\bwapi-data\bwapi.ini".

**Comment by heinermann** [comment] 2015-04-23 00:14
I'm not getting an array subscript out of range for the code you provided.

The crash is expected behaviour because Game::getRegionAt returns nullptr for invalid positions. This information was missing from the documentation.

**Comment by ratiotile** [comment] 2015-04-23 01:59
The full code is at http://pastebin.com/p8BUUQ3H
I merely added those 3 lines into the Example Client.
The issue was hard to narrow down because everything looks ok after the call to Game::getRegionAt. With the typedef of the RegionImpl pointer, is it still possible to compare Region r == nullptr ?

Wouldn't it be better to throw an exception right away if the position arg is invalid? I don't see the value in giving back a null pointer.

**Comment by heinermann** [comment] 2015-04-24 00:57
Why would you want to code with exceptions?

~~~
Position pos(-1, -1);
BWAPI::Region test_region(Broodwar->getRegionAt(pos));  // everything still OK
if (test_region != nullptr) {
    Broodwar << "Region ID is " << test_region->getID() << " accessible? " << test_region->isAccessible() << std::endl;
}
~~~
vs
~~~
Position pos(-1, -1);
try
{
    BWAPI::Region test_region(Broodwar->getRegionAt(pos));  // everything still OK
    Broodwar << "Region ID is " << test_region->getID() << " accessible? " << test_region->isAccessible() << std::endl;
}
catch (??????)
{
}
~~~

It's the same scenario when you receive a nullptr for Unit or Player.
Alternatively if you want to use the closest location inside of the map bounds, you can use [Position::makeValid](http://bwapi.github.io/singleton_b_w_a_p_i_1_1_point.html#a686e096d4ebc50fcb4e7be0042ccf614).

~~~
Position pos(-1, -1);
BWAPI::Region test_region(Broodwar->getRegionAt(pos.makeValid()));  // everything still OK
Broodwar << "Region ID is " << test_region->getID() << " accessible? " << test_region->isAccessible() << std::endl;
~~~

In terms of API changes I don't know if we should have a dummy Region for out of bounds locations or if we should just leave the current return value.

**Comment by ratiotile** [comment] 2015-04-24 02:06
I see your point in just leaving the return as nullptr. A Regions::Invalid dummy would also work, and goes along with Positions::Invalid, though you would need to make one for Unit too. A change to throw exceptions would be incompatible with existing codebases.

When I wrote a c++ bot I never had the problem dealing with nullptr: as you said, I would just check the pointer each time. The issue was in producing a Python wrapper that could deal with the null pointer. It can't crash to desktop without a way to catch/check it. I ruled out pos.makeValid() since it is too easy to forget it, and there is no indication where in the code the crash is coming from. What I have done instead is to throw an exception in the wrapper as soon as the nullptr is returned. An example:

    ##Python
    for unit in units:
        try:
            target = unit.getTarget()
            Broodwar.drawLineMap(target.getPosition(), unit.getPosition(), cybw.Colors.White)
        except cybw.NullPointerException:
            continue

A strong reason to use exceptions instead is that it would help to people write more stable bots, once they learned how to deal with them. Why should functions ever return nullptr? There is no reason to keep around nullptrs. You are going to check it immediately and then discard it if it is null. Best part is, if you forget to use try/catch, your code blows up immediately vs. forgetting to check `== nullptr` and having a null Region that might turn up later and cause a crash. The two ways basically take up the same amount of code, too. However, null-checking might take more code if you check in each function (defensive programming).

10 lines:

    Position pos(-1, -1);
    BWAPI::Region test_region(Broodwar->getRegionAt(pos));
    if (test_region != nullptr) 
    {
        Broodwar << "Region ID is " << test_region->getID();
    }
    else
    {
        Broodwar << "invalid Region";
    }

still 10 lines with exceptions:

    Position pos(-1, -1);
    try
    {
        BWAPI::Region test_region(Broodwar->getRegionAt(pos));
        Broodwar << "Region ID is " << test_region->getID();
    }
    catch(exception& e)
    {
        Broodwar << "invalid Region";
    }

Think about it.

In any case, BWAPI probably shouldn't change this right now. I bet there are far more pressing issues to resolve.

**Comment by heinermann** [comment] 2015-04-27 02:47
I'm going to close this since it is intended behaviour.

**Closed by heinermann** 2015-04-27 02:47 UTC
Labels: bug, Priority-Critical, question
