### ISSUE TITLE
"Local PC" game mode doesn't work on Windows 10

### ISSUE THREAD

**Issue by davechurchill** [bwapi/bwapi#614] opened 2015-09-19 21:09 UTC
On Windows 10: 
- Have BWAPI / Starcraft installed normally (everything else works)
- Select Local PC network mode
- Select a profile in the Registry page
- Click "OK"
- Get this error: http://i.imgur.com/zpOJlbv.png
- When I click Cancel to debug, I get this prompt in Visual Studio 2013: http://i.imgur.com/wyBUCn0.png
- Hitting Break I get the following info: http://i.imgur.com/E2PzyQB.png

This appears to happen for BWAPI 3.7.4 and BWAPI 4.1.2 (the only two I've tested)

I am pretty sure this is a Windows 10 issue because if I copy the Starcraft and Chaoslauncher folders to a Windows 7 virtual machine, the same steps produce no error and Local PC mode works as intended.

I believe this is high priority because it makes testing bots against other bots on a single machine almost impossible.

**Comment by davechurchill** [comment] 2015-09-20 02:43
Fixed by setting Chaoslauncher and Starcraft to run as administrator

**Comment by heinermann** [comment] 2015-09-20 03:38
That is a workaround, not a fix. The issue is likely because the network module isn't using the security stuff like BWAPI used. There was a similar issue before about BWAPI itself requiring administrative privileges.

**Comment by heinermann** [comment] 2016-07-17 03:45
Going to close this since @blole seems to have fixed it. If any additional Windows 10 issues comes up, feel free to create a new issue.

**Closed by heinermann** 2016-07-17 03:45 UTC
Labels: bug, Priority-Low
